version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    command: ["server", "/data"]
volumes:
  minio_data:
