version: '3.8'
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    env_file:
      - .env
    cap_add:
      - IPC_LOCK
    command: ["server", "-dev"]
